name: Run Selenium tests

on:
  push:
    branches:
      - main

jobs:
  selenium:
    name: Run Selenium tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and run Node.js tests
      run: |
        cd login
        npm install
        node server.js
    - name: navigate back
      run: |
        cd ..
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build and Run Selenium tests
      run: |
        cd SeleniumCode
        javac -cp ".:path/to/selenium-server-standalone.jar" src/org/example/*.java
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.MobileResponsivenessTest
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.PWATestFour
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.PWATestThree
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.PWATestTwo
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.PWATestOne
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.TestManifest
