name: Run Selenium tests

on:
  push:
    branches:
      - main

jobs:
  selenium:
    name: Run Selenium tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and run Node.js tests
      run: |
        cd login
        npm install
    - name: navigate back
      run: |
        cd ..
        
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build and Run Selenium tests
      run: |
        cd SeleniumCode
        javac -cp ".:path/to/selenium-server-standalone.jar" src/org/example/PWATestOne.java
        java -cp ".:path/to/selenium-server-standalone.jar" org.example.PWATestOne
